config: add missing include for non-glibc after ad6d734d51a3
src/config.c:477:14: error: use of undeclared identifier 'PATH_MAX'
                        char path[PATH_MAX];
                                  ^